### ISSUE TITLE
Some issue with c2me

### ISSUE THREAD

**Issue by coco875** [Sweet-Berry-Collective/Wandering-Wizardry#10]
when I play on my modpack I have this error who appears in log
```log
Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-1)
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231646!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231646!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.next(CheckedThreadLocalRandom.java:86) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231646!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:27) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/wwizardry@1.1.1+mc.1.21.1-neoforge/dev.sweetberry.wwizardry.content.entity.Snail$Variant.randomNonSlug(Snail.java:203) ~[wwizardry-1.1.1+mc.1.21.1-neoforge.jar%23732!/:?]
	at TRANSFORMER/wwizardry@1.1.1+mc.1.21.1-neoforge/dev.sweetberry.wwizardry.content.entity.Snail.<init>(Snail.java:52) ~[wwizardry-1.1.1+mc.1.21.1-neoforge.jar%23732!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.create(net/minecraft/world/entity/EntityType.java:1097) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.NaturalSpawner.spawnMobsForChunkGeneration(net/minecraft/world/level/NaturalSpawner.java:389) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.spawnOriginalMobs(net/minecraft/world/level/levelgen/NoiseBasedChunkGenerator.java:454) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateSpawn(ChunkStatusTasks.java:180) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.mixinextras$bridge$doWork$14(ChunkStep.java) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.wrapOperation$dhj000$c2me_opts_chunk_access$runGenerationTask(com/ishland/c2me/opts/chunk_access/mixin/region_capture/MixinChunkGenerationStep.java [c2me-opts-chunk-access.mixins.json]:26) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.apply(net/minecraft/world/level/chunk/status/ChunkStep.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23455!/:?]
	at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0alpha.0.1501.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-rewrites-chunk-system-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231657!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.1501.21.1/com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-base-mc1.21.1-0.3.0+alpha.0.150-all_mapped_moj_1.21.1.jar%231642!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.1501.21.1/com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-base-mc1.21.1-0.3.0+alpha.0.150-all_mapped_moj_1.21.1.jar%231642!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.1501.21.1/com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-base-mc1.21.1-0.3.0+alpha.0.150-all_mapped_moj_1.21.1.jar%231642!/:?]
```

**Comment by Oliver-makes-code** [comment]
This issue cannot be easily fixed. C2ME does a lot of stuff that makes it incompatible with worldgen mods.

**Comment by TropheusJ** [comment]
this is very simple to fix, you just need to use the entity random instead of the world random
