### ISSUE TITLE
[NeoForge] Missing trade for villager type: wwizardry:fungal_forest

### ISSUE THREAD

**Issue by Linguardium** [Sweet-Berry-Collective/Wandering-Wizardry#8]
appears when attempting to create a new world

```
Caused by: java.lang.IllegalStateException: Missing trade for villager type: wwizardry:fungal_forest
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.npc.VillagerTrades$EmeraldsForVillagerTypeItem.lambda$new$1(VillagerTrades.java:1134) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?] {re:classloading}
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.npc.VillagerTrades$EmeraldsForVillagerTypeItem.<init>(VillagerTrades.java:1133) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.npc.VillagerTrades.lambda$static$0(VillagerTrades.java:145) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.Util.make(Util.java:461) ~[client-1.21.1-20240808.144430-srg.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.npc.VillagerTrades.<clinit>(VillagerTrades.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.common.VillagerTradingManager.<clinit>(VillagerTradingManager.java:28) ~[?:?] {re:classloading}
```

**Comment by Oliver-makes-code** [comment]
This looks to be an issue affecting fabric too, it's just deferred until the villager variant is created in-world
